### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [borkdude/balcony#1]
Hi, I want to design a new logo for the project completely free...

**Comment by borkdude** [comment]
Hey @Arslanshn, that's very kind of you!

I consider this a hobby script, so I'm not sure if it deserves a logo yet.

Can I ask you for other projects when the time and size is right? Do you have any examples online?

Kind regards,

Michiel

**Comment by Arslanshn** [comment]
I'd love to be subject to the
